### ISSUE TITLE
O3DE Stabilization/2409 Branch Compile Errors

### ISSUE THREAD

**Issue by AMZN-Gene** [PopcornFX/O3DEPopcornFXPlugin#76]
Latest main Popcorn FX has compile errors when built against O3DE stabilization/2409
This is strange because the error is due to using a deleted class, _ScriptCanvasRegistry_, but this class hasn't existed for many months in both development and 2409.

https://github.com/o3de/o3de/commit/92b5dcc4ee65d3b96c8026d878ae7e0e9681334c

 
**Repro**
1. Pull O3DE 2409 release branch
2. Compile game using popcorn fx (such as Multiplayer Sample

**Excepted Result**
Game compiles

**Actual Result**
```
6>D:\prj\multiplayersample\build\windows\External\O3DEPopcornFXPlugin-61405827\Code\Azcg\Generated\PopcornFX.Static\AutoGenNodeableRegistry.generated.h(33,18): error C2504: 'ScriptCanvasRegistry': base class undefined
6>D:\prj\multiplayersample\build\windows\External\O3DEPopcornFXPlugin-61405827\Code\Azcg\Generated\PopcornFX.Static\AutoGenNodeableRegistry.generated.h(40,14): error C3668: 'ScriptCanvas::PopcornFXStaticNodeableRegistry::Init': method with override specifier 'override' did not override any base class methods
6>D:\prj\multiplayersample\build\windows\External\O3DEPopcornFXPlugin-61405827\Code\Azcg\Generated\PopcornFX.Static\AutoGenNodeableRegistry.generated.h(41,14): error C3668: 'ScriptCanvas::PopcornFXStaticNodeableRegistry::Reflect': method with override specifier 'override' did not override any base class methods
6>D:\prj\multiplayersample\build\windows\External\O3DEPopcornFXPlugin-61405827\Code\Azcg\Generated\PopcornFX.Static\AutoGenNodeableRegistry.generated.h(42,49): error C3668: 'ScriptCanvas::PopcornFXStaticNodeableRegistry::GetComponentDescriptors': method with override specifier 'override' did not override any base class methods
```

https://github.com/o3de/o3de/commit/92b5dcc4ee65d3b96c8026d878ae7e0e9681334c

**Comment by AMZN-Gene** [comment]
2409 O3DE_VERSION_MAJOR is reporting 2, but cmake is looking for version 3.

https://github.com/PopcornFX/O3DEPopcornFXPlugin/blob/development/Code/CMakeLists.txt#L41-L47

**Comment by ValPKFX** [comment]
As said in the discord thread, this is caused by the version downgrade on Stabilization/2409 from https://github.com/o3de/o3de/pull/17903.
Since it seems the problem of versioning will be discussed, I made a temp fix to make it work with 24.09 on our development branch [8ec714f](https://github.com/PopcornFX/O3DEPopcornFXPlugin/commit/8ec714f474dad27e837f5826bdfbf4db6964cf60).
This will also be included in the next releases.

**Comment by AMZN-Gene** [comment]
Other's are having the same problem with versioning. It's going to be discussed during the next TSC meeting. Let's hold off on any versioning check changes until there's clarity after the next TSC.
